openapi: 3.0.0
info:
  version: 2.0.0
  title: An include file to define Application endpoints
  license:
    name: Apache 2.0
paths:
  /api/applications:
    post:
      operationId: createApplication
      summary: Create an Application
      description: Create an Application
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      requestBody:
        $ref: '#/components/requestBodies/CreateApplicationInput'
      responses:
        '201':
          description: Application created
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/ResourceCreatedResponse'
        '400':
          description: Bad request
    get:
      operationId: listApplications
      summary: List Applications
      description: List Applications
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - $ref: '../api.yml#/components/parameters/nameSearch'
      security:
        - bearer_token: []
      tags:
        - Application
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListApplicationResponse'
        '400':
          description: Bad request
  /api/applications/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadApplication
      summary: Get Application
      description: Get Application
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      responses:
        '200':
          description: Application record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
        '404':
          description: Application not found
    put:
      operationId: updateApplication
      summary: Update Application
      description: Update Application
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      requestBody:
        $ref: '#/components/requestBodies/UpdateApplicationInput'
      responses:
        '204':
          description: Application update succeeded
        '400':
          description: Bad request
        '404':
          description: Application not found
    delete:
      operationId: removeApplication
      summary: Remove Application
      description: Remove Application
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      responses:
        '204':
          description: Application record was deleted
        '404':
          description: Application not found
  /api/applications/{id}/devices/bulk-create:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    post:
      operationId: bulkCreateDevices
      summary: Add many devices
      description: Add many devices to an application
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      requestBody:
        $ref: '#/components/requestBodies/BulkCreateDeviceInput'
      responses:
        '200':
          description: List of items that report information and status on the creation of each device
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/BulkCreateDeviceResponse'
        '400':
          description: Bad request
components:
  schemas:
    Application:
      type: object
      properties:
        name:
          type: string
          description: The Application's name
        description:
          type: string
          description: The Application's description
        baseUrl:
          type: string
          description: The URL that the Reporting Protocol sends the data to. This may have additional paths added, depending on the Reporting Protocol.
        reportingProtocolId:
          type: string
          description: The ID of the Reporting Protocol the Application will use to pass Device data back to the Application Vendor
    ApplicationResponse:
       allOf:
        - $ref: '#/components/schemas/Application'
        - type: object
          properties:
            id:
              type: string
            running:
              type: boolean
              description: If the Application is currently forwarding uplink and downlink messages
    ListApplicationResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          required:
            - records
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/ApplicationResponse'
              default: []
    BulkCreateDeviceItemInput:
      type: object
      required:
        - devEUI
      properties:
        name:
          type: string
          description: Name of the device
        description:
          type: string
          description: Description of the device
        devEUI:
          type: string
          description: Device's unique devEUI
    BulkCreateDeviceResponse:
      type: array
      items:
        type: object
        properties:
          status:
            type: string
            enum:
              - OK
              - ERROR
          deviceId:
            type: string
            description: ID of the created device
          devEUI:
            type: string
            description: Device's devEUI
          row:
            type: integer
            descripton: The index of the device in the array that was posted.
          error:
            type: string
            description: Failure reason
  requestBodies:
    CreateApplicationInput:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Application'
              - type: object
                required:
                  - name
      description: Application to be created
      required: true
    UpdateApplicationInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Application'
      description: Application properties to be updated
      required: true
    BulkCreateDeviceInput:
      content:
        application/json:
          schema:
            type: object
            required:
              - deviceProfileId
              - devices
            properties:
              deviceProfileId:
                type: string
                description: The ID of the device profile for the devices being imported
              devices:
                type: array
                items:
                  $ref: '#/components/schemas/BulkCreateDeviceItemInput'
                  minLength: 1
