openapi: 3.0.0
info:
  version: 1.2.1
  title: An include file to define Application endpoints
  license:
    name: Apache 2.0
paths:
  /api/applications:
    post:
      operationId: createApplication
      summary: Create an Application
      description: Create an Application
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      requestBody:
        $ref: '#/components/requestBodies/CreateApplicationInput'
      responses:
        '200':
          description: Application created
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/ResourceCreatedResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '400':
          description: Bad request
    get:
      operationId: listApplications
      summary: List Applications
      description: List Applications
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - $ref: '../api.yml#/components/parameters/nameSearch'
        - name: companyId
          in: query
          required: false
          schema:
            type: string
        - name: reportingProtocolId
          in: query
          required: false
          schema:
            type: string
      security:
        - bearer_token: []
      tags:
        - Application
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListApplicationResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '400':
          description: Bad request
  /api/applications/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadApplication
      summary: Get Application
      description: Get Application
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      responses:
        '200':
          description: Application record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: Application not found
    put:
      operationId: updateApplication
      summary: Update Application
      description: Update Application
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      requestBody:
        $ref: '#/components/requestBodies/UpdateApplicationInput'
      responses:
        '204':
          description: Application update succeeded
        '400':
          description: Bad request
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: Application not found
    delete:
      operationId: deleteApplication
      summary: Delete Application
      description: Delete Application
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      responses:
        '204':
          description: Application record was deleted
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: Application not found
  /api/applications/{id}/bulk-device-import:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    post:
      operationId: bulkCreateDevices
      summary: Add several devices to an application
      description: Add many devices to an application
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      requestBody:
        $ref: '#/components/requestBodies/BulkCreateDeviceInput'
      responses:
        '200':
          description: List of items that report information and status on the creation of each device
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/BulkCreateDeviceResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '400':
          description: Bad request
  /api/applications/{id}/start:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    post:
      operationId: startApplication
      summary: Start application
      description: Enable application to forward uplinks and downlinks
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      responses:
        '200':
          description: Application was started. Response contains logs from remote networks.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/applications/{id}/stop:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    post:
      operationId: stopApplication
      summary: Stop application
      description: Disable application from forwarding uplinks and downlinks
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Application
      responses:
        '200':
          description: Application was stopped. Response contains logs from remote networks.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/ingest/:applicationId/:networkId:
    parameters:
      - name: applicationId
        in: path
        description: ID of application
        required: true
        schema:
          type: string
      - name: networkId
        in: path
        description: ID of network sending device uplink
        required: true
        schema:
          type: string
    post:
      operationId: receiveUplink
      summary: Receive uplink
      description: Receive a device uplink from a remove network
      parameters: []
      security: []
      tags:
        - Application
      requestBody:
        $ref: '#/components/requestBodies/UplinkInput'
      responses:
        '204':
          description: 'Uplink received'

components:
  schemas:
    Application:
      type: object
      properties:
        name:
          type: string
          description: The Application's name
        description:
          type: string
          description: The Application's description
        companyId:
          type: string
          description: The ID of the Company to which the Application belongs. For a Company Admin user, this can only be the Id of their own Company.
        baseUrl:
          type: string
          description: The URL that the Reporting Protocol sends the data to. This may have additional paths added, depending on the Reporting Protocol.
        reportingProtocolId:
          type: string
          description: The ID of the Reporting Protocol the Application will use to pass Device data back to the Application Vendor
    ApplicationResponse:
       allOf:
        - $ref: '#/components/schemas/Application'
        - type: object
          properties:
            id:
              type: string
            running:
              type: boolean
              description: If the Application is currently sending data received from the Networks to the baseUrl via the Reporting Protocol
    ListApplicationResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/ApplicationResponse'
              default: []
    BulkCreateDeviceItemInput:
      type: object
      required:
        - devEUI
      properties:
        name:
          type: string
          description: Name of the device
        description:
          type: string
          description: Description of the device
        devEUI:
          type: string
          description: Device's unique devEUI
    BulkCreateDeviceResponse:
      type: array
      items:
        type: object
        properties:
          status:
            type: string
            enum:
              - OK
              - ERROR
          deviceId:
            type: string
            description: ID of the created device
          devEUI:
            type: string
            description: Device's devEUI
          row:
            type: integer
            format: int32
            descripton: The index of the device in the array that was posted.
          error:
            type: string
            description: Failure reason
  requestBodies:
    CreateApplicationInput:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Application'
              - type: object
                required:
                  - name
                  - companyId
      description: Application to be created
      required: true
    UpdateApplicationInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Application'
      description: Application properties to be updated
      required: true
    BulkCreateDeviceInput:
      content:
        application/json:
          schema:
            required:
              - deviceProfileId
              - devices
            properties:
              deviceProfileId:
                type: string
                description: The ID of the device profile for the devices being imported
              devices:
                type: array
                items:
                  $ref: '#/components/schemas/BulkCreateDeviceItemInput'
                  minLength: 1
    UplinkInput:
      content:
        application/json:
          schema:
            type: object
