openapi: 3.0.0
info:
  version: 2.0.0
  title: An include file to define ApplicationNetworkTypeLink endpoints
  license:
    name: Apache 2.0
paths:
  /api/application-network-type-links:
    post:
      operationId: createApplicationNetworkTypeLink
      summary: Create an ApplicationNetworkTypeLink
      description: Create an ApplicationNetworkTypeLink
      parameters: []
      security:
        - bearer_token: []
      tags:
        - ApplicationNetworkTypeLink
      requestBody:
        $ref: '#/components/requestBodies/CreateApplicationNetworkTypeLinkInput'
      responses:
        '200':
          description: ApplicationNetworkTypeLink created
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/ResourceCreatedResponse'
        '400':
          description: Bad request
    get:
      operationId: listApplicationNetworkTypeLink
      summary: List ApplicationNetworkTypeLinks
      description: List ApplicationNetworkTypeLinks
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - $ref: '../api.yml#/components/parameters/applicationId'
        - $ref: '../api.yml#/components/parameters/networkTypeId'
      security:
        - bearer_token: []
      tags:
        - ApplicationNetworkTypeLink
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListApplicationNetworkTypeLinkResponse'
        '400':
          description: Bad request
  /api/application-network-type-links/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadApplicationNetworkTypeLink
      summary: Get ApplicationNetworkTypeLink
      description: Get ApplicationNetworkTypeLink
      parameters: []
      security:
        - bearer_token: []
      tags:
        - ApplicationNetworkTypeLink
      responses:
        '200':
          description: ApplicationNetworkTypeLink record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationNetworkTypeLinkResponse'
        '404':
          description: ApplicationNetworkTypeLink not found
    patch:
      operationId: updateApplicationNetworkTypeLink
      summary: Update ApplicationNetworkTypeLink
      description: Update ApplicationNetworkTypeLink
      parameters: []
      security:
        - bearer_token: []
      tags:
        - ApplicationNetworkTypeLink
      requestBody:
        $ref: '#/components/requestBodies/UpdateApplicationNetworkTypeLinkInput'
      responses:
        '204':
          description: ApplicationNetworkTypeLink update succeeded
        '400':
          description: Bad request
        '404':
          description: ApplicationNetworkTypeLink not found
    delete:
      operationId: removeApplicationNetworkTypeLink
      summary: Remove ApplicationNetworkTypeLink
      description: Remove ApplicationNetworkTypeLink
      parameters: []
      security:
        - bearer_token: []
      tags:
        - ApplicationNetworkTypeLink
      responses:
        '204':
          description: ApplicationNetworkTypeLink record was deleted
        '404':
          description: ApplicationNetworkTypeLink not found
  /api/application-network-type-links/{id}/push:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    post:
      operationId: pushApplicationNetworkTypeLink
      summary: Push ApplicationNetworkTypeLink
      description: Push Application to all Networks of this NetworkType
      parameters:
        - $ref: '../api.yml#/components/parameters/pushDevices'
      security:
        - bearer_token: []
      tags:
        - ApplicationNetworkTypeLink
      responses:
        '204':
          description: ApplicationNetworkTypeLink was pushed
        '404':
          description: ApplicationNetworkTypeLink not found
components:
  schemas:
    ApplicationNetworkTypeLink:
      type: object
      properties:
        applicationId:
          type: string
          description: The Application the record is linking to the NetworkType
        networkTypeId:
          type: string
          description: The NetworkType to which the Application is linked
        networkSettings:
          type: object
          description: The settings that correspond to the NetworkType
        enabled:
          type: boolean
          description: Whether or not messages are forwarded for this application and network type
    ApplicationNetworkTypeLinkResponse:
       allOf:
        - type: object
          properties:
            id:
              type: string
        - $ref: '#/components/schemas/ApplicationNetworkTypeLink'
    ListApplicationNetworkTypeLinkResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/ApplicationNetworkTypeLinkResponse'
              default: []
  requestBodies:
    CreateApplicationNetworkTypeLinkInput:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ApplicationNetworkTypeLink'
              - type: object
                required:
                  - applicationId
                  - networkTypeId
      description: ApplicationNetworkTypeLink to be created
      required: true
    UpdateApplicationNetworkTypeLinkInput:
      content:
        application/json:
          schema:
            type: object
            properties:
              networkSettings:
                type: object
                description: The settings that correspond to the NetworkType
      description: ApplicationNetworkTypeLink properties to be updated
      required: true
