openapi: 3.0.0
info:
  version: 1.2.1
  title: An include file to define CompanyNetworkTypeLink endpoints
  license:
    name: Apache 2.0
paths:
  /api/companyNetworkTypeLinks:
    post:
      operationId: createCompanyNetworkTypeLink
      summary: Create a CompanyNetworkTypeLink
      description: Create a CompanyNetworkTypeLink, available only to company administrators
      parameters: []
      security:
        - bearer_token: []
      tags:
        - CompanyNetworkTypeLink
      requestBody:
        $ref: '#/components/requestBodies/CreateCompanyNetworkTypeLinkInput'
      responses:
        '200':
          description: CompanyNetworkTypeLink created
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/ResourceCreatedResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '400':
          description: Bad request
    get:
      operationId: listCompanyNetworkTypeLinks
      summary: List CompanyNetworkTypeLinks
      description: List CompanyNetworkTypeLinks, restricted according to company admins
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - name: companyId
          in: query
          description: The ID of the Company
          required: false
          schema:
            type: string
        - name: networkTypeId
          in: query
          description: The ID of the Network
          required: false
          schema:
            type: string
      security:
        - bearer_token: []
      tags:
        - CompanyNetworkTypeLink
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCompanyNetworkTypeLinkResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '400':
          description: Bad request
  /api/companyNetworkTypeLinks/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadCompanyNetworkTypeLink
      summary: Get CompanyNetworkTypeLink
      description: Get CompanyNetworkTypeLink
      parameters: []
      security:
        - bearer_token: []
      tags:
        - CompanyNetworkTypeLink
      responses:
        '200':
          description: CompanyNetworkTypeLink record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyNetworkTypeLinkResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: CompanyNetworkTypeLink not found
    put:
      operationId: updateCompanyNetworkTypeLink
      summary: Update CompanyNetworkTypeLink
      description: Update CompanyNetworkTypeLink, available only to company administrators
      parameters: []
      security:
        - bearer_token: []
      tags:
        - CompanyNetworkTypeLink
      requestBody:
        $ref: '#/components/requestBodies/UpdateCompanyNetworkTypeLinkInput'
      responses:
        '204':
          description: CompanyNetworkTypeLink update succeeded
        '400':
          description: Bad request
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: CompanyNetworkTypeLink not found
    delete:
      operationId: removeCompanyNetworkTypeLink
      summary: Remove CompanyNetworkTypeLink
      description: Remove CompanyNetworkTypeLink, available only to company administrators
      parameters: []
      security:
        - bearer_token: []
      tags:
        - CompanyNetworkTypeLink
      responses:
        '204':
          description: CompanyNetworkTypeLink record was deleted
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: CompanyNetworkTypeLink not found
components:
  schemas:
    CompanyNetworkTypeLink:
      type: object
      properties:
        companyId:
          type: string
          description: The Company the record is linking to the NetworkType
        networkTypeId:
          type: string
          description: The NetworkType to which the Company is linked
        networkSettings:
          type: string
          description: The settings in a JSON string that correspond to the NetworkType
    CompanyNetworkTypeLinkResponse:
       allOf:
        - $ref: '#/components/schemas/CompanyNetworkTypeLink'
        - type: object
          properties:
            id:
              type: string
    ListCompanyNetworkTypeLinkResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/CompanyNetworkTypeLinkResponse'
              default: []
  requestBodies:
    CreateCompanyNetworkTypeLinkInput:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/CompanyNetworkTypeLink'
              - type: object
                required:
                  - companyId
                  - networkTypeId
                  - networkSettings
      description: CompanyNetworkTypeLink to be created
      required: true
    UpdateCompanyNetworkTypeLinkInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CompanyNetworkTypeLink'
      description: CompanyNetworkTypeLink properties to be updated
      required: true
