openapi: 3.0.0
info:
  version: 2.0.0
  title: An include file to define DeviceNetworkTypeLink endpoints
  license:
    name: Apache 2.0
paths:
  /api/device-network-type-links:
    post:
      operationId: createDeviceNetworkTypeLink
      summary: Create a DeviceNetworkTypeLink
      description: Create a DeviceNetworkTypeLink
      parameters: []
      security:
        - bearer_token: []
      tags:
        - DeviceNetworkTypeLink
      requestBody:
        $ref: '#/components/requestBodies/CreateDeviceNetworkTypeLinkInput'
      responses:
        '200':
          description: DeviceNetworkTypeLink created
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/ResourceCreatedResponse'
        '400':
          description: Bad request
    get:
      operationId: listDeviceNetworkTypeLink
      summary: List DeviceNetworkTypeLinks
      description: List DeviceNetworkTypeLinks
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - $ref: '../api.yml#/components/parameters/deviceId'
        - $ref: '../api.yml#/components/parameters/applicationId'
        - $ref: '../api.yml#/components/parameters/networkTypeId'
      security:
        - bearer_token: []
      tags:
        - DeviceNetworkTypeLink
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDeviceNetworkTypeLinkResponse'
        '400':
          description: Bad request
  /api/device-network-type-links/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadDeviceNetworkTypeLink
      summary: Get DeviceNetworkTypeLink
      description: Get DeviceNetworkTypeLink
      parameters: []
      security:
        - bearer_token: []
      tags:
        - DeviceNetworkTypeLink
      responses:
        '200':
          description: DeviceNetworkTypeLink record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceNetworkTypeLinkResponse'
        '404':
          description: DeviceNetworkTypeLink not found
    put:
      operationId: updateDeviceNetworkTypeLink
      summary: Update DeviceNetworkTypeLink
      description: Update DeviceNetworkTypeLink
      parameters: []
      security:
        - bearer_token: []
      tags:
        - DeviceNetworkTypeLink
      requestBody:
        $ref: '#/components/requestBodies/UpdateDeviceNetworkTypeLinkInput'
      responses:
        '204':
          description: DeviceNetworkTypeLink update succeeded
        '400':
          description: Bad request
        '404':
          description: DeviceNetworkTypeLink not found
    delete:
      operationId: removeDeviceNetworkTypeLink
      summary: Remove DeviceNetworkTypeLink
      description: Remove DeviceNetworkTypeLink
      parameters: []
      security:
        - bearer_token: []
      tags:
        - DeviceNetworkTypeLink
      responses:
        '204':
          description: DeviceNetworkTypeLink record was deleted
        '404':
          description: DeviceNetworkTypeLink not found
  /api/device-network-type-links/{id}/push:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    post:
      operationId: pushDeviceNetworkTypeLink
      summary: Push DeviceNetworkTypeLink
      description: Push Device to all Networks of this NetworkType
      security:
        - bearer_token: []
      tags:
        - DeviceNetworkTypeLink
      responses:
        '204':
          description: DeviceNetworkTypeLink was pushed
        '404':
          description: DeviceNetworkTypeLink not found
components:
  schemas:
    DeviceNetworkTypeLink:
      type: object
      properties:
        deviceId:
          type: string
          description: The Application the record is linking to the NetworkType
        networkTypeId:
          type: string
          description: The NetworkType to which the Application is linked
        deviceProfileId:
          type: string
          description: The DeviceProfile from which this device receives network settings
        networkSettings:
          type: object
          description: The settings that correspond to the NetworkType
        enabled:
          type: boolean
          description: Whether or not messages are forwarded for this application and network type
    DeviceNetworkTypeLinkResponse:
       allOf:
        - $ref: '#/components/schemas/DeviceNetworkTypeLink'
        - type: object
          properties:
            id:
              type: string
    ListDeviceNetworkTypeLinkResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/DeviceNetworkTypeLinkResponse'
              default: []
  requestBodies:
    CreateDeviceNetworkTypeLinkInput:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DeviceNetworkTypeLink'
              - type: object
                required:
                  - deviceId
                  - networkTypeId
                  - deviceProfileId
      description: DeviceNetworkTypeLink to be created
      required: true
    UpdateDeviceNetworkTypeLinkInput:
      content:
        application/json:
          schema:
            type: object
            properties:
              networkSettings:
                type: object
                description: The settings in a JSON string that correspond to the NetworkType
      description: DeviceNetworkTypeLink properties to be updated
      required: true
