openapi: 3.0.0
info:
  version: 2.0.0
  title: An include file to define DeviceProfile endpoints
  license:
    name: Apache 2.0
paths:
  /api/device-profiles:
    post:
      operationId: createDeviceProfile
      summary: Create a DeviceProfile
      description: Create a DeviceProfile
      parameters: []
      security:
        - bearer_token: []
      tags:
        - DeviceProfile
      requestBody:
        $ref: '#/components/requestBodies/CreateDeviceProfileInput'
      responses:
        '200':
          description: DeviceProfile created
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/ResourceCreatedResponse'
        '400':
          description: Bad request
    get:
      operationId: listDeviceProfile
      summary: List DeviceProfiles
      description: List DeviceProfiles
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - $ref: '../api.yml#/components/parameters/nameSearch'
        - $ref: '../api.yml#/components/parameters/networkTypeId'
      security:
        - bearer_token: []
      tags:
        - DeviceProfile
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDeviceProfileResponse'
        '400':
          description: Bad request
  /api/device-profiles/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadDeviceProfile
      summary: Get DeviceProfile
      description: Get DeviceProfile
      parameters: []
      security:
        - bearer_token: []
      tags:
        - DeviceProfile
      responses:
        '200':
          description: DeviceProfile record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceProfileResponse'
        '404':
          description: DeviceProfile not found
    patch:
      operationId: updateDeviceProfile
      summary: Update DeviceProfile
      description: Update DeviceProfile
      parameters: []
      security:
        - bearer_token: []
      tags:
        - DeviceProfile
      requestBody:
        $ref: '#/components/requestBodies/UpdateDeviceProfileInput'
      responses:
        '204':
          description: DeviceProfile update succeeded
        '400':
          description: Bad request
        '404':
          description: DeviceProfile not found
    delete:
      operationId: removeDeviceProfile
      summary: Remove DeviceProfile
      description: Remove DeviceProfile
      parameters: []
      security:
        - bearer_token: []
      tags:
        - DeviceProfile
      responses:
        '204':
          description: DeviceProfile record was deleted
        '404':
          description: DeviceProfile not found
  /api/device-profiles/{id}/push:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    post:
      operationId: pushDeviceProfile
      summary: Push DeviceProfile
      description: Push DeviceProfile to all Networks of this NetworkType
      parameters:
        - $ref: '../api.yml#/components/parameters/pushDevices'
      security:
        - bearer_token: []
      tags:
        - DeviceProfile
      responses:
        '204':
          description: DeviceProfile was pushed
        '404':
          description: DeviceProfile not found
components:
  schemas:
    DeviceProfile:
      type: object
      properties:
        name:
          type: string
          description: The Device Profile's name
        description:
          type: string
          description: The Device Profile's description
        networkTypeId:
          type: string
          description: The NetworkType for this DeviceProfile
        networkSettings:
          type: object
          description: The settings that correspond to the NetworkType
    DeviceProfileResponse:
       allOf:
        - type: object
          properties:
            id:
              type: string
        - $ref: '#/components/schemas/DeviceProfile'
    ListDeviceProfileResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/DeviceProfileResponse'
              default: []
  requestBodies:
    CreateDeviceProfileInput:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DeviceProfile'
              - type: object
                required:
                  - name
                  - networkTypeId
      description: DeviceProfile to be created
      required: true
    UpdateDeviceProfileInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceProfile'
      description: DeviceProfile properties to be updated
      required: true
