openapi: 3.0.0
info:
  version: 2.0.0
  title: An include file to define Device endpoints
  license:
    name: Apache 2.0
paths:
  /api/devices:
    post:
      operationId: createDevice
      summary: Create a Device
      description: Create a Device
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Device
      requestBody:
        $ref: '#/components/requestBodies/CreateDeviceInput'
      responses:
        '200':
          description: Device created
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/ResourceCreatedResponse'
        '400':
          description: Bad request
    get:
      operationId: listDevices
      summary: List Devices
      description: List Devices
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - $ref: '../api.yml#/components/parameters/nameSearch'
        - $ref: '../api.yml#/components/parameters/applicationId'
      security:
        - bearer_token: []
      tags:
        - Device
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDeviceResponse'
        '400':
          description: Bad request
  /api/devices/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadDevice
      summary: Get Device
      description: Get Device
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Device
      responses:
        '200':
          description: Device record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceResponse'
        '404':
          description: Device not found
    put:
      operationId: updateDevice
      summary: Update Device
      description: Update Device
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Device
      requestBody:
        $ref: '#/components/requestBodies/UpdateDeviceInput'
      responses:
        '204':
          description: Device update succeeded
        '400':
          description: Bad request
        '404':
          description: Device not found
    delete:
      operationId: removeDevice
      summary: Remove Device
      description: Remove Device
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Device
      responses:
        '204':
          description: Device record was deleted
        '404':
          description: Device not found
  /api/devices/{id}/downlinks:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    post:
      operationId: sendUnicastDownlink
      summary: Send unicast downlink
      description: Send a unicast downlink to one device
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Device
      requestBody:
        $ref: '#/components/requestBodies/UnicastDownlinkInput'
      responses:
        '200':
          description: Downlink was sent. Response contains meta obtained from sending the downlink.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmittedUnicastDownlinkResponse'
        '404':
          description: Device not found
  /api/uplinks:
    post:
      operationId: sendUplink
      summary: Send uplink to application server.
      description: Send a message to the application server.  x509 client certificate is required. Certificate must contain devEUI as the subject CN.
      parameters: []
      security: []
      tags:
        - Device
      requestBody:
        $ref: '#/components/requestBodies/UplinkInput'
      responses:
        '204':
          description: Uplink forwarded to application server
        '404':
          description: Unable to locate device with matching devEUI
  /api/downlinks:
    get:
      operationId: listDownlinks
      summary: Get device downlinks
      description: Get queued downlinks for one device. x509 client certificate is required. Certificate must contain devEUI as the subject CN. Long-polling supported.
      parameters:
        - name: prefer
          in: header
          description: Use 'wait=n' as the header value, where n is seconds.  If no downlinks available at time of request, request will wait for n seconds before returning.
          required: false
          schema:
            type: string
      security: []
      tags:
        - Device
      responses:
        '200':
          description: List of downlinks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDownlinkResponse'
        '404':
          description: Unable to locate device with matching devEUI
  /api/uplinks/{applicationId}/{networkId}:
    parameters:
      - name: applicationId
        in: path
        description: ID of application
        required: true
        schema:
          type: string
      - name: networkId
        in: path
        description: ID of network sending device uplink
        required: true
        schema:
          type: string
    post:
      operationId: sendUplinkAsNetwork
      summary: Send uplink from a network
      description: Send a device uplink from a remote IoT network
      parameters: []
      security: []
      tags:
        - Device
      requestBody:
        $ref: '#/components/requestBodies/UplinkInput'
      responses:
        '204':
          description: Uplink forwarded to application server
        '404':
          description: Unable to find either Network or Application
components:
  schemas:
    Device:
      type: object
      properties:
        name:
          type: string
          description: The Device's name
        description:
          type: string
          description: The Device's description
        deviceModel:
          type: string
          description: The Device's Model information
        applicationId:
          type: string
          description: The ID of the Application to which the device belongs
    DeviceResponse:
       allOf:
        - $ref: '#/components/schemas/Device'
        - type: object
          properties:
            id:
              type: string
    ListDeviceResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/DeviceResponse'
              default: []
    Downlink:
      type: object
      required:
        - fCnt
        - fPort
      properties:
        fCnt:
          type: integer
          description: Application's downlink frame counter
        fPort:
          type: integer
          description: The intended port for LoRa devices
        data:
          type: string
          description: Any string to send as data to the device
        jsonObject:
          type: object
          description: A JSON object to send to the device
    SubmittedDownlinkResponseItem:
      type: object
      properties:
        devEUI:
          type: string
        status:
          type: string
          enum:
            - SENT
            - FAILED
            - QUEUED
        statusCode:
          type: string
          description: Status code received from network if message sent via HTTP
        error:
          type: string
          description: Reason for failure
    SubmittedUnicastDownlinkResponse:
      type: array
      items:
        $ref: '#/components/schemas/SubmittedDownlinkResponseItem'
    ListDownlinkResponse:
      type: array
      items:
        $ref: '#/components/schemas/Downlink'
  requestBodies:
    CreateDeviceInput:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Device'
              - type: object
                required:
                  - name
                  - description
                  - applicationId
                  - deviceModel
      description: Device to be created
      required: true
    UpdateDeviceInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Device'
      description: Device properties to be updated
      required: true
    UnicastDownlinkInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Downlink'
    UplinkInput:
      content:
        application/json:
          schema:
            type: object
