openapi: 3.0.0
info:
  version: 2.0.0
  title: An include file to define NetworkProtocol endpoints
  license:
    name: Apache 2.0
paths:
  /api/network-protocols:
    get:
      operationId: listNetworkProtocol
      summary: List NetworkProtocols
      description: List NetworkProtocols, available only to system administrators
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - $ref: '../api.yml#/components/parameters/nameSearch'
      security:
        - bearer_token: []
      tags:
        - NetworkProtocol
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListNetworkProtocolResponse'
        '400':
          description: Bad request
  /api/network-protocols/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadNetworkProtocol
      summary: Get NetworkProtocol
      description: Get NetworkProtocol
      parameters: []
      security:
        - bearer_token: []
      tags:
        - NetworkProtocol
      responses:
        '200':
          description: NetworkProtocol record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkProtocolResponse'
        '404':
          description: NetworkProtocol not found
components:
  schemas:
    NetworkProtocol:
      type: object
      properties:
        name:
          type: string
        protocolHandler:
          type: string
          description: Path to file that contains the handler code, relative to the handlers dir
        networkTypeId:
          type: string
        networkProtocolVersion:
          type: string
    NetworkProtocolResponse:
       allOf:
        - $ref: '#/components/schemas/NetworkProtocol'
        - type: object
          properties:
            id:
              type: string
    ListNetworkProtocolResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/NetworkProtocolResponse'
              default: []
