openapi: 3.0.0
info:
  version: 1.2.1
  title: An include file to define NetworkProtocol endpoints
  license:
    name: Apache 2.0
paths:
  /api/networkProtocols:
    post:
      operationId: createNetworkProtocol
      summary: Create a NetworkProtocol
      description: Create a NetworkProtocol, available only to system administrators
      parameters: []
      security:
        - bearer_token: []
      tags:
        - NetworkProtocol
      requestBody:
        $ref: '#/components/requestBodies/CreateNetworkProtocolInput'
      responses:
        '200':
          description: NetworkProtocol created
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/ResourceCreatedResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '400':
          description: Bad request
    get:
      operationId: listNetworkProtocols
      summary: List NetworkProtocols
      description: List NetworkProtocols, available only to system administrators
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - $ref: '../api.yml#/components/parameters/nameSearch'
      security:
        - bearer_token: []
      tags:
        - NetworkProtocol
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListNetworkProtocolResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '400':
          description: Bad request
  /api/networkProtocols/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadNetworkProtocol
      summary: Get NetworkProtocol
      description: Get NetworkProtocol
      parameters: []
      security:
        - bearer_token: []
      tags:
        - NetworkProtocol
      responses:
        '200':
          description: NetworkProtocol record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkProtocolResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: NetworkProtocol not found
    put:
      operationId: updateNetworkProtocol
      summary: Update NetworkProtocol
      description: Update NetworkProtocol, available only to system administrators
      parameters: []
      security:
        - bearer_token: []
      tags:
        - NetworkProtocol
      requestBody:
        $ref: '#/components/requestBodies/UpdateNetworkProtocolInput'
      responses:
        '204':
          description: NetworkProtocol update succeeded
        '400':
          description: Bad request
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: NetworkProtocol not found
    delete:
      operationId: deleteNetworkProtocol
      summary: Delete NetworkProtocol
      description: Delete NetworkProtocol, available only to system administrators
      parameters: []
      security:
        - bearer_token: []
      tags:
        - NetworkProtocol
      responses:
        '204':
          description: NetworkProtocol record was deleted
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: NetworkProtocol not found
  /api/networkProtocolHandlers:
    get:
      operationId: getNetworkProtocolHandlers
      summary: Get NetworkProtocol handlers
      description: Get list of NetworkProtocol handler file paths
      parameters: []
      security:
        - bearer_token: []
      tags:
        - NetworkProtocol
      responses:
        '200':
          description: Array of NetworkProtocol handler file paths
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListNetworkProtocolHandlerResponse'
        '403':
          description: Authenticated user not allowed to perform this operation

components:
  schemas:
    NetworkProtocol:
      type: object
      properties:
        name:
          type: string
        protocolHandler:
          type: string
          description: Path to file that contains the handler code, relative to the handlers dir
        networkTypeId:
          type: string
    NetworkProtocolResponse:
       allOf:
        - $ref: '#/components/schemas/NetworkProtocol'
        - type: object
          properties:
            id:
              type: string
    ListNetworkProtocolResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/NetworkProtocolResponse'
              default: []
    ListNetworkProtocolHandlerResponse:
      type: array
      items:
        type: string
      default: []
  requestBodies:
    CreateNetworkProtocolInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NetworkProtocol'
      description: NetworkProtocol to be created
      required: true
    UpdateNetworkProtocolInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NetworkProtocol'
      description: NetworkProtocol properties to be updated
      required: true
