openapi: 3.0.0
info:
  version: 2.0.0
  title: An include file to define NetworkType endpoints
  license:
    name: Apache 2.0
paths:
  /api/networkTypes:
    get:
      operationId: listNetworkTypes
      summary: List NetworkTypes
      description: List NetworkTypes, available only to system administrators
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - $ref: '../api.yml#/components/parameters/nameSearch'
      security:
        - bearer_token: []
      tags:
        - NetworkType
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListNetworkTypeResponse'
        '400':
          description: Bad request
  /api/networkTypes/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadNetworkType
      summary: Get NetworkType
      description: Get NetworkType
      parameters: []
      security:
        - bearer_token: []
      tags:
        - NetworkType
      responses:
        '200':
          description: NetworkType record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkTypeResponse'
        '404':
          description: NetworkType not found
components:
  schemas:
    NetworkType:
      type: object
      required:
        - name
        - version
      properties:
        name:
          type: string
        version:
          type: string
    NetworkTypeResponse:
       allOf:
        - $ref: '#/components/schemas/NetworkType'
        - type: object
          properties:
            id:
              type: string
    ListNetworkTypeResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/NetworkTypeResponse'
              default: []
