openapi: 3.0.0
info:
  version: 1.2.1
  title: An include file to define company PasswordPolicy endpoints
  license:
    name: Apache 2.0
paths:
  /api/passwordPolicies:
    post:
      operationId: createPasswordPolicy
      summary: Create a PasswordPolicy
      description: Create a PasswordPolicy, available only to company administrators
      parameters: []
      security:
        - bearer_token: []
      tags:
        - PasswordPolicy
      requestBody:
        $ref: '#/components/requestBodies/CreatePasswordPolicyInput'
      responses:
        '200':
          description: PasswordPolicy created
          content:
            application/json:
              schema:
                $ref: '../api.yml#/components/schemas/ResourceCreatedResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '400':
          description: Bad request
  /api/passwordPolicies/company/{companyId}:
    parameters:
      - name: companyId
        in: path
        description: ID of company
        required: true
        schema:
          type: string
    get:
      operationId: getCompanyPasswordPolicies
      summary: Get all company PasswordPolicies
      description: Get all company PasswordPolicies, available only to company administrators
      parameters: []
      security:
        - bearer_token: []
      tags:
        - PasswordPolicy
      responses:
        '200':
          description: PasswordPolicy query successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPasswordPolicyResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '400':
          description: Bad request
  /api/passwordPolicies/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadPasswordPolicy
      summary: Get PasswordPolicy
      description: Get PasswordPolicy
      parameters: []
      security:
        - bearer_token: []
      tags:
        - PasswordPolicy
      responses:
        '200':
          description: PasswordPolicy record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordPolicyResponse'
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: PasswordPolicy not found
    put:
      operationId: updatePasswordPolicy
      summary: Update PasswordPolicy
      description: Update PasswordPolicy, available only to company administrators
      parameters: []
      security:
        - bearer_token: []
      tags:
        - PasswordPolicy
      requestBody:
        $ref: '#/components/requestBodies/UpdatePasswordPolicyInput'
      responses:
        '204':
          description: PasswordPolicy update succeeded
        '400':
          description: Bad request
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: PasswordPolicy not found
    delete:
      operationId: deletePasswordPolicy
      summary: Delete PasswordPolicy
      description: Delete PasswordPolicy, available only to company administrators
      parameters: []
      security:
        - bearer_token: []
      tags:
        - PasswordPolicy
      responses:
        '204':
          description: PasswordPolicy record was deleted
        '403':
          description: Authenticated user not allowed to perform this operation
        '404':
          description: PasswordPolicy not found
components:
  schemas:
    PasswordPolicy:
      type: object
      properties:
        ruleText:
          type: string
          description: The Password Policy's description, intended for display to the end user.
        ruleRegExp:
          type: string
          description: The Password Policy's regular expression, which must "match" the entered password for it to be considered valid.
        companyId:
          type: string
          description: The id of the company that this Password Policy belongs to. If not supplied, for a System Admin, defaults to null (global rule for all users/companies). For Company Admin, defaults to the user's companyId. If specified by a Company Admin, it MUST match their own company.
    PasswordPolicyResponse:
      allOf:
        - $ref: '#/components/schemas/PasswordPolicy'
        - type: object
          properties:
            id:
              type: string
    ListPasswordPolicyResponse:
      type: array
      items:
        $ref: '#/components/schemas/PasswordPolicyResponse'
      default: []
  requestBodies:
    CreatePasswordPolicyInput:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/PasswordPolicy'
              - type: object
                required:
                  - ruleText
                  - ruleRegExp
      description: PasswordPolicy to be created
      required: true
    UpdatePasswordPolicyInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PasswordPolicy'
      description: PasswordPolicy properties to be updated
      required: true
