openapi: 3.0.0
info:
  version: 2.0.0
  title: An include file to define ReportingProtocol endpoints
  license:
    name: Apache 2.0
paths:
  /api/reporting-protocols:
    get:
      operationId: listReportingProtocol
      summary: List ReportingProtocols
      description: List ReportingProtocols, available only to system administrators
      parameters:
        - $ref: '../api.yml#/components/parameters/offsetParam'
        - $ref: '../api.yml#/components/parameters/limitParam'
        - $ref: '../api.yml#/components/parameters/nameSearch'
      security:
        - bearer_token: []
      tags:
        - ReportingProtocol
      responses:
        '200':
          description: Query response with totalCount and list of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListReportingProtocolResponse'
        '400':
          description: Bad request
  /api/reporting-protocols/{id}:
    parameters:
      - $ref: '../api.yml#/components/parameters/idParam'
    get:
      operationId: loadReportingProtocol
      summary: Get ReportingProtocol
      description: Get ReportingProtocol
      parameters: []
      security:
        - bearer_token: []
      tags:
        - ReportingProtocol
      responses:
        '200':
          description: ReportingProtocol record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportingProtocolResponse'
        '404':
          description: ReportingProtocol not found
components:
  schemas:
    ReportingProtocol:
      type: object
      properties:
        name:
          type: string
        protocolHandler:
          type: string
          description: Path to file that contains the handler code, relative to the handlers dir
    ReportingProtocolResponse:
       allOf:
        - $ref: '#/components/schemas/ReportingProtocol'
        - type: object
          properties:
            id:
              type: string
    ListReportingProtocolResponse:
      allOf:
        - $ref: '../api.yml#/components/schemas/ListResponse'
        - type: object
          properties:
            records:
              type: array
              items:
                $ref: '#/components/schemas/ReportingProtocolResponse'
              default: []
