openapi: 3.0.0
info:
  version: 2.0.0
  title: An include file to define Session endpoints
  license:
    name: Apache 2.0
paths:
  /api/sessions:
    post:
      operationId: createSession
      summary: Create a Session
      description: Submit a user's credentials and receive a JWT token
      parameters: []
      security: []
      tags:
        - Session
      requestBody:
        $ref: '#/components/requestBodies/LoginCredentials'
      responses:
        '200':
          description: JWT as response body
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
    delete:
      operationId: removeSession
      summary: Remove a Session
      description: Invalidate the user's current jwt token
      parameters: []
      security:
        - bearer_token: []
      tags:
        - Session
      responses:
        '204':
          description: No content
        '401':
          description: Unauthorized
components:
  requestBodies:
    LoginCredentials:
      content:
        application/json:
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      description: User's login credentials
      required: true
