
version: '3.5'
services:
  lpwanserver:
    build:
      context: ../
      dockerfile: development/Dockerfile
    volumes:
      - ../app:/usr/src/app
      - ../certs:/usr/src/certs
      - ./config.json:/usr/src/config.json
    ports:
      - 3200:3200
    networks:
      - lpwanserver_dev
    environment:
      - port=3200
      - config_file=../config.json
      - public_dir=
networks:
  lpwanserver_dev:
    name: lpwanserver_dev
