openapi: 3.0.0
servers: []
info:
  description: >-
    This service goes between an IoT application server and the various networks
    to which the devices connect.  LPWAN Server uses extensions to support
    additional networks.
  version: 1.2.1
  title: LPWAN Server
  termsOfService: ''
  contact:
    email: d.malas@cablelabs.com
    name: Darly Malas
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
securitySchemes:
  bearer_token:
    type: http
    scheme: bearer
    bearerFormat: JWT
tags:
  - name: Session
    description: Operations about session
  - name: User
    description: Operations about user
  - name: Company
    description: Operations about company
  - name: PasswordPolicy
paths:
  /api/sessions:
    $ref: 'endpoints/session.yml#/paths/~1api~1sessions'
  /api/users:
    $ref: 'endpoints/user.yml#/paths/~1api~1users'
  /api/users/{id}:
    $ref: 'endpoints/user.yml#/paths/~1api~1users~1{id}'
  /api/users/me:
    $ref: 'endpoints/user.yml#/paths/~1api~1users~1me'
  /api/users/verifyEmail/{uuid}:
    $ref: 'endpoints/user.yml#/paths/~1api~1users~1verifyEmail~1{uuid}'
  /api/companies:
    $ref: 'endpoints/company.yml#/paths/~1api~1companies'
  /api/companies/{id}:
    $ref: 'endpoints/company.yml#/paths/~1api~1companies~1{id}'
components:
  parameters:
    idParam:
      name: id
      in: path
      description: ID of resource
      required: true
      schema:
        type: string
    offsetParam:
      name: offset
      in: query
      description: Number of records to skip
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
    limitParam:
      name: limit
      in: query
      description: Max records to return
      required: false
      schema:
        type: integer
        format: int32
  schemas:
    ResourceCreatedResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    ListResponse:
      type: object
      required:
        - totalCount
        - records
      properties:
        totalCount:
          type: integer
          format: int32
        records:
          type: Array
          default: []
