language: node_js
sudo: required
node_js:
  - "10.15.3"
services:
  - docker
install:
  - npm ci
before_script:
  - npm run package
script:
  - npm run test:unit
  - npm run test:api
  - npm run test:e2e
after_success: npm run coverage
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push lpwanserver/lpwanserver
  on:
    branch: master
