version: '3.5'

services:
  lpwanserver:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: lpwanserver/lpwanserver
    container_name: lpwanserver
    networks:
      - lpwanserver_dev
    ports:
      - '3200:3200'
    environment:
      - port=3200
      - config_file=config/dev.json
      - public_dir=public
    volumes:
      - ../certs:/usr/src/app/certs

networks:
  lpwanserver_dev:
    name: lpwanserver_dev
