version: '3'

services:
  rest:
    image: lpwanserver/lpwanserver
    links:
      - loraserver
      - lora_appserver
    depends_on:
      - loraserver
      - lora_appserver
    environment:
      - NODE_ENV=local
      - PORT=3200
    ports:
      - '3200:3200'

  loraserver:
    image: loraserver/loraserver:2
    depends_on:
      - postgresql
      - redis
      - mosquitto
    volumes:
      - ./configuration/loraserver:/etc/loraserver

  lora_appserver:
    image: loraserver/lora-app-server:2
    depends_on:
      - postgresql
      - redis
      - mosquitto
    ports:
      - 8080:8080
    volumes:
      - ./configuration/lora-app-server:/etc/lora-app-server
  
  postgresql:
    image: postgres:9.6-alpine
    ports:
      - 5432
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    ports:
      - 6379
    image: redis:4-alpine
    volumes:
      - ./../data/redis:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883