version: '3.5'

services:
  loraserver:
    image: loraserver/loraserver:2
    networks:
      - lpwanserver_net
    depends_on:
      - postgresql
      - redis
      - mosquitto
    volumes:
      - ./configuration/loraserver:/etc/loraserver

  loraserver1:
    image: loraserver/loraserver:1
    networks:
      - lpwanserver_net
    depends_on:
      - postgresql
      - redis
      - mosquitto
    volumes:
    - ./configuration/loraserver_1:/etc/loraserver

  lora_appserver:
    image: loraserver/lora-app-server:2
    networks:
      - lpwanserver_net
    depends_on:
      - postgresql
      - redis
      - mosquitto
    ports:
      - 8080:8080
    volumes:
      - ./configuration/lora-app-server:/etc/lora-app-server

  lora_appserver1:
    image: loraserver/lora-app-server:1
    networks:
      - lpwanserver_net
    depends_on:
      - postgresql
      - redis
      - mosquitto
    ports:
      - 8081:8080
    volumes:
      - ./configuration/lora-app-server_1:/etc/lora-app-server

  postgresql:
    image: postgres:9.6-alpine
    container_name: dev_lpwanserver_loraserver_postgres
    networks:
      - lpwanserver_net
    ports:
      - 5432
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - lpwanserver_loraserver_postgres:/var/lib/postgresql/data

  redis:
    networks:
      - lpwanserver_net
    ports:
      - 6379
    image: redis:4-alpine

  mosquitto:
    image: eclipse-mosquitto
    networks:
      - lpwanserver_net
    ports:
      - 1883:1883

networks:
  lpwanserver_net:
    name: lpwanserver_net
volumes:
  lpwanserver_loraserver_postgres: