version: '3.5'

services:
  lpwanserver:
    image: lpwanserver/lpwanserver:latest
    container_name: lpwanserver
    environment:
      - port=3200
      - prisma_protocol=http
      - prisma_host=prisma
      - prisma_port=4466
    ports:
      - 3200:3200
    networks:
      - lpwanserver
    volumes:
      - "../data/production.sqlite3:/app/data/production.sqlite3:consistent"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
        max_attempts: 3

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "4000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - lpwanserver

networks:
  lpwanserver:
    name: lpwanserver
