version: '3.5'

services:
  lpwanserver:
    image: lpwanserver/lpwanserver:latest
    networks:
      - lpwanserver_dev
    environment:
      - port=3200
      - prisma_protocol=http
      - prisma_host=prisma
      - prisma_port=4466
    ports:
      - 3200:3200
    volumes:
      - ../certs:/usr/src/app/certs
networks:
  lpwanserver_dev:
    name: lpwanserver_dev
