version: '3.5'

services:
  lpwanserver:
    image: lpwanserver/lpwanserver
    container_name: lpwanserver_demo
    networks:
      - lpwanserver_dev
    ports:
      - '3200:3200'
    depends_on:
      - loraserver
      - lora_appserver
      - loraserver1
      - lora_appserver1
    environment:
      - port=3200
      - config_file=config/dev.json
      - public_dir=public/build
    volumes:
      - ../certs:/usr/src/app/certs

  loraserver:
    image: loraserver/loraserver:2
    container_name: lpwanserver_dev_loraserver2
    networks:
      - lpwanserver_dev
    depends_on:
      - postgresql
      - redis
      - mosquitto
    volumes:
      - ./dev/loraserver/configuration/loraserver:/etc/loraserver

  loraserver1:
    image: loraserver/loraserver:1
    container_name: lpwanserver_dev_loraserver1
    networks:
      - lpwanserver_dev
    depends_on:
      - postgresql
      - redis
      - mosquitto
    volumes:
    - ./dev/loraserver/configuration/loraserver_1:/etc/loraserver

  lora_appserver:
    image: loraserver/lora-app-server:2
    container_name: lpwanserver_dev_loraappserver2
    networks:
      - lpwanserver_dev
    depends_on:
      - postgresql
      - redis
      - mosquitto
    ports:
      - 8082:8080
    volumes:
      - ./dev/loraserver/configuration/lora-app-server:/etc/lora-app-server

  lora_appserver1:
    image: loraserver/lora-app-server:1
    container_name: lpwanserver_dev_loraappserver1
    networks:
      - lpwanserver_dev
    depends_on:
      - postgresql
      - redis
      - mosquitto
    ports:
      - 8081:8080
    volumes:
      - ./dev/loraserver/configuration/lora-app-server_1:/etc/lora-app-server

  postgresql:
    image: postgres:9.6-alpine
    container_name: lpwanserver_dev_loraserver_postgres
    networks:
      - lpwanserver_dev
    ports:
      - 5432
    volumes:
      - ./dev/loraserver/configuration/postgresql/initdb-demo:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    container_name: lpwanserver_dev_loraserver_redis
    networks:
      - lpwanserver_dev
    ports:
      - 6379

  mosquitto:
    image: eclipse-mosquitto
    container_name: lpwanserver_dev_loraserver_mosquitto
    networks:
      - lpwanserver_dev
    ports:
      - 1883:1883

networks:
  lpwanserver_dev:
    name: lpwanserver_dev
volumes:
  postgres:
    name: lpwanserver_dev_loraserver_postgres
