version: '3.5'

services:
  prisma:
    image: prismagraphql/prisma:1.33
    container_name: lpwanserver_dev_prisma
    networks:
      - lpwanserver_dev
    ports:
    - "4466:4466"
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma

  postgres:
    image: postgres:10.8-alpine
    container_name: lpwanserver_dev_postgres
    networks:
      - lpwanserver_dev
    ports:
      - 5432
    volumes:
      - ../../../data:/baseline-data
      - ../configuration/postgresql/initdb-demo:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    container_name: lpwanserver_dev_redis
    networks:
      - lpwanserver_dev
    ports:
      - 6379
    volumes:
      - redis:/data

networks:
  lpwanserver_dev:
    name: lpwanserver_dev
volumes:
  postgres:
    name: lpwanserver_dev_postgres
  redis:
    name: lpwanserver_dev_redis
