version: '3.5'
services:
  prisma:
    image: prismagraphql/prisma:1.28
    container_name: lpwanserver_dev_prisma
    networks:
      - lpwanserver_dev
    ports:
    - "4466:4466"
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            database: prisma
            schema: public
            user: prisma
            password: prisma
            rawAccess: true
            port: '5432'
            migrations: false
  postgres:
    image: postgres:10.3
    container_name: lpwanserver_dev_postgres
    networks:
      - lpwanserver_dev
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ../../data:/baseline-data
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: lpwanserver_dev_postgres
networks:
  lpwanserver_dev:
    name: lpwanserver_dev